### PR TITLE
Feature issue56

### PR DESCRIPTION
**Pull request by end2endzone**
This is to reintegrate issue56 branch into master branch.
Fixes issue #56.

Review the changes and mark them as ready for merge.

Please **do not** "allow squash merging".

### CODE REVIEW

**Review by GasDauMin — APPROVED** [review]
I have read the code changes, I have no reason why it could not be approved. The problem is solved, the style of the algorithm as always clear and thoughtful and finally implemented case testing.

**Comment by end2endzone** [comment]
Thank you for reveiweing the changes.
Would you like to proceed and merge the pull request into the master branch ?

**Comment by GasDauMin** [comment]
Sure, I can try :)

I can do all the steps from the github web environment with "Merge pull request" and "Create a merge commit" option.
And also as You can see I just don’t communicate very fluently in English and won’t know exactly what to write in a commit comment if appropriate i will describe very abstractly using the information found in commits of this branch.

**Comment by end2endzone** [comment]
As far as I know, the commit messages wont be lost after the merge in master. This is why I asked you to not "squash" the commits as this option would squeeze all the commits of the branch into **a single one** potentially loosing the details of the changes.

Please do not worry about the quality of your English. I can understand you perfectly fine. English is not my native language either and I sometimes have the feeling that yours is better than mine.

I would be happy with a comment as general as "Reintegrating issue #56 into master branch." The details of the changes are already in each commit logs and the reason for the change is also documented in the issue.

**Comment by GasDauMin** [comment]
Done, changes merged. Thank you for your efforts and assistance in making improvements that are relevant to me. :)

**Pull request merged**
