### PR TITLE
Fixed a long comment bug and redesigned document validating

### LINKED ISSUE #78: Syntax error in default.xml
According to [XML rules](https://www.w3.org/TR/REC-xml/#sec-comments), for compatibility reason it is better not to use '--' in the comments section.

image

### LINKED ISSUE #80: Comment inside XML
I'am trying to add comment inside the document, at the begining of document and when coment reach some amount of bits it is not loaded at all. 

image

After some time of reviewing, I found a problematic method **Configuration::IsValidConfigFile** it peeks only small portion of configuration file and that portion may not cover important tags like `root`, `shell`, or `menu`.

image

I thinking maybe it would be better to do check with XML parse tools?

### PR DESCRIPTION
**Pull request by GasDauMin**
Resolves #78 , resolves #80

### CODE REVIEW

**Comment by end2endzone** [comment]
Just for curiosity, do you know a quick way to modify the box layout characters if I need to increase the columns width ? The reasons I used `--` sequences is because the layout could easily be edited with https://www.tablesgenerator.com/markdown_tables. Also the content of `default.xml` was partially synchronized with `UserManual.md`.

**Review by end2endzone — COMMENTED** [review]
I am uncertain about your proposition. I do not think that parsing the file with an XML parser is the best way to solve your problem. It is true that 

your proposition is solving the issue but there are two things that I do not like:
1. It is now duplicating the "loading" code and also duplicating the way a _Configuration File_ is loaded. Both `Configuration::IsValidConfigFile()` and 

`Configuration::LoadFile()` will have to be modified if a correction is required.
2. Each file are now parsed twice before loading. A single xml file is first parsed in `Configuration::IsValidConfigFile()` when validated [here]

(https://github.com/end2endzone/ShellAnything/blob/master/src/ConfigManager.cpp#L104) and then it is deleted/discarded and then a second time when it is 

actually loaded [here](https://github.com/end2endzone/ShellAnything/blob/master/src/ConfigManager.cpp#L113).

When I have written `Configuration::IsValidConfigFile()` function, the purpose was to quickly discard files that was not _Configuration Files_. This was 

for performance reason. It we parse twice each file, I think it defies the performance purpose.

I think it would be a better idea to completely delete the function `Configuration::IsValidConfigFile()` and rethink how [ConfigManager::Refresh()]

(https://github.com/end2endzone/ShellAnything/blob/master/src/ConfigManager.cpp#L60) is implemented. For example, we could simply remove [line 104]

(https://github.com/end2endzone/ShellAnything/blob/master/src/ConfigManager.cpp#L104) and let the line `Configuration * config = 

Configuration::LoadFile(file_path, error);` deal with actual file loading. If we try to load an invalid file, a NULL _Configuration_ will be returned.

What do you think ?

**Comment by GasDauMin** [comment]
Maybe we could to leave extension check, for example I store not only xml files but also logs and icons in ShellAnything sub-forlders.

**Comment by end2endzone** [comment]
Yes. I like what you proposed. From what I understand, we should rewrite `Configuration::IsValidConfigFile()` to only validate based on the file's extension. This will strongly limit the possibility of loading invalid files. It wont duplicate code. If a user eventually store XML files in his configuration directory, then it shall open a new issue to solve the problem.

Please proceed with the corrections. Push your changes again to the same branch. I think GitHub will pick up the changes and update the pull request. Add a message in this PR once done (so that I will be notified by email)

**Comment by GasDauMin** [comment]
In **IsValidConfigFile** method I left extension check only.

**Review by end2endzone — APPROVED** [review]
Good!

**Pull request merged**
